all:
	g++ -std=c++14 -Wall main.cpp forAll.cpp formula.cpp equal.cpp var.cpp card.cpp arrayAccessor.cpp different.cpp intersection.cpp disjonction.cpp conjonction.cpp -o main.exe

clean:
	rm -f *.o main
